version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run linting
          command: yarn run lint --no-fix --max-warnings=0
      - run:
          name: Build the app
          command: yarn run build
